version: '3'

services:
  eu-web1:
    build: docker_images/target_machine
    env_file:
    - docker_env

  eu-web2:
    build: docker_images/target_machine
    env_file:
    - docker_env

  ansible:
    build: docker_images/ansible
    depends_on:
    - eu-web1
    - eu-web2
    working_dir: /work
    volumes:
    - ./:/work
    command: bash -c "hostname; ssh eu-web1 \"hostname\""
